#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace DontGetSidetracked.EditorTools
{
    /// <summary>
    /// Production-only validation for the RuStore Pay configuration generated by the official Unity plugin.
    /// Runtime/gameplay code stays independent from the SDK settings type; the editor reads the asset through
    /// SerializedObject so SDK upgrades do not leak concrete editor types into the game architecture.
    /// </summary>
    public sealed class RuStorePayReleaseContractValidator : IPreprocessBuildWithReport
    {
        private const string ManifestPath = "Assets/Plugins/Android/AndroidManifest.xml";
        private static readonly Regex DeeplinkSchemePattern =
            new Regex("^[A-Za-z][A-Za-z0-9+.-]*$", RegexOptions.CultureInvariant);
        private static readonly Regex ConsoleAppIdPattern =
            new Regex("^[0-9]+$", RegexOptions.CultureInvariant);

        public int callbackOrder => -990;

        [MenuItem("Tools/НЕ СБЕЙСЯ!/Validate RuStore Pay Release Contract")]
        public static void ValidateMenu()
        {
            List<string> errors = CollectErrors();
            if (errors.Count == 0)
            {
                Debug.Log("RuStore Pay release contract passed.");
                return;
            }

            throw new BuildFailedException("RuStore Pay release contract failed:\n- " + string.Join("\n- ", errors));
        }

        public void OnPreprocessBuild(BuildReport report)
        {
            if (report.summary.platform != BuildTarget.Android) return;
            if ((report.summary.options & BuildOptions.Development) != 0) return;

            List<string> errors = CollectErrors();
            if (errors.Count > 0)
                throw new BuildFailedException("Android production build blocked by RuStore Pay preflight:\n- " +
                                               string.Join("\n- ", errors));
        }

        internal static List<string> CollectErrors()
        {
            var errors = new List<string>();
            ValidatePayClientSettings(errors);
            ValidatePatchedManifest(errors);
            return errors;
        }

        private static void ValidatePayClientSettings(List<string> errors)
        {
            string[] guids = AssetDatabase.FindAssets("PayClientSettings t:ScriptableObject");
            if (guids == null || guids.Length == 0)
            {
                errors.Add(
                    "Create the official PayClientSettings.asset via Window → RuStoreSDK → Settings → PayClient, " +
                    "then configure the RuStore Console application ID and a unique deeplink scheme.");
                return;
            }

            if (guids.Length > 1)
                errors.Add("Multiple PayClientSettings assets were found. Keep exactly one production Pay Client configuration.");

            string assetPath = AssetDatabase.GUIDToAssetPath(guids[0]);
            ScriptableObject settings = AssetDatabase.LoadAssetAtPath<ScriptableObject>(assetPath);
            if (settings == null)
            {
                errors.Add("PayClientSettings.asset could not be loaded: " + assetPath);
                return;
            }

            var serialized = new SerializedObject(settings);
            SerializedProperty consoleApplicationId = serialized.FindProperty("consoleApplicationId");
            SerializedProperty deeplinkScheme = serialized.FindProperty("deeplinkScheme");
            SerializedProperty schemeVersion = serialized.FindProperty("schemeVersion");

            if (consoleApplicationId == null)
            {
                errors.Add("PayClientSettings.asset has no consoleApplicationId field. Open it in the current RuStore Pay SDK and migrate the settings schema.");
            }
            else
            {
                string value = consoleApplicationId.stringValue?.Trim() ?? string.Empty;
                if (!ConsoleAppIdPattern.IsMatch(value))
                    errors.Add("PayClientSettings consoleApplicationId must be the numeric application ID from RuStore Console.");
            }

            if (deeplinkScheme == null)
            {
                errors.Add("PayClientSettings.asset has no deeplinkScheme field. Open it in the current RuStore Pay SDK and migrate the settings schema.");
            }
            else
            {
                string value = deeplinkScheme.stringValue?.Trim() ?? string.Empty;
                if (!DeeplinkSchemePattern.IsMatch(value))
                    errors.Add("PayClientSettings deeplinkScheme must be non-empty and use an RFC-3986-compatible URI scheme (letters first; then letters, digits, +, -, .). ");
                if (string.Equals(value, "nesbeisya", StringComparison.OrdinalIgnoreCase))
                    errors.Add("Use a dedicated RuStore Pay deeplink scheme instead of the gameplay challenge scheme 'nesbeisya'.");
            }

            if (schemeVersion == null)
                errors.Add("PayClientSettings.asset has no schemeVersion. Run the RuStore Pay settings migration before production release.");
        }

        private static void ValidatePatchedManifest(List<string> errors)
        {
            if (!File.Exists(ManifestPath))
            {
                errors.Add("AndroidManifest.xml is missing; enable Custom Main Manifest and patch it with RuStore Pay settings.");
                return;
            }

            string manifest = File.ReadAllText(ManifestPath);
            Require(manifest, "com.unity3d.player.UnityPlayerActivity", errors,
                "RuStore Pay requires UnityPlayerActivity as the Android application entry point.");
            Require(manifest, "@string/rustore_PayClientSettings_deeplinkScheme", errors,
                "Run Window → RuStoreSDK → Settings → PayClient → Patch Manifest so the Pay deeplink scheme comes from generated resources.");
            Require(manifest, "console_app_id_value", errors,
                "RuStore Pay console_app_id_value meta-data is missing. Patch the manifest from PayClientSettings.");
            Require(manifest, "internal_config_key", errors,
                "RuStore Pay internal_config_key meta-data is missing. Patch the manifest from PayClientSettings.");
            Require(manifest, "sdk_pay_scheme_value", errors,
                "RuStore Pay sdk_pay_scheme_value meta-data is missing. Patch the manifest from PayClientSettings.");

            bool hasOfficialDeeplinkActivity =
                manifest.IndexOf("ru.rustore.unitysdk.RuStoreDeeplinkActivityDefault", StringComparison.Ordinal) >= 0 ||
                manifest.IndexOf("ru.rustore.unitysdk.RuStoreIntentFilterActivity", StringComparison.Ordinal) >= 0;
            if (!hasOfficialDeeplinkActivity)
            {
                errors.Add(
                    "RuStore Pay deeplink Activity is missing. Use the current PayClient Settings 'Patch Manifest' action; " +
                    "do not route payment callbacks through the gameplay challenge intent-filter.");
            }
        }

        private static void Require(string text, string token, List<string> errors, string error)
        {
            if (text.IndexOf(token, StringComparison.Ordinal) < 0)
                errors.Add(error);
        }
    }
}
#endif
